-- Consulta completa dos produtos com características, preços e loja

SELECT
    P.ID_PRODUTO,
    P.NOME AS NOME_PRODUTO,
    P.MARCA,
    P.CATEGORIA,
    P.URL_IMAGEM,
    C.TIPO_USO,
    C.GENERO_DESTINADO,
    C.COR_PREDOMINANTE,
    C.TAMANHO_DISPONIVEL,
    L.NOME AS NOME_LOJA,
    L.URL_SITE,
    PP.PRECO_LISTADO,
    PP.PRECO_PROMOCIONAL,
    PP.URL_PAGINA_PRODUTO,
    TO_CHAR(PP.DATA_COTACAO, 'DD/MM/YYYY') AS DATA_COTACAO
FROM
    FO_PRODUTO P
JOIN FO_CARACTERISTICA_PRODUTO C ON P.ID_PRODUTO = C.ID_PRODUTO
JOIN FO_PRECO_PRODUTO PP ON P.ID_PRODUTO = PP.ID_PRODUTO
JOIN FO_LOJA L ON PP.ID_LOJA = L.ID_LOJA
ORDER BY
    P.ID_PRODUTO;
